cyclomatic_complexity:
    warning: 15
    error: 20

function_body_length:
    warning: 75
    error: 100

disabled_rules:
    - todo
    - trailing_whitespace
    - trailing_comma
    - trailing_newline
    - identifier_name
    - type_name
    - multiple_closures_with_trailing_closure
    - type_body_length
    - line_length
    - opening_brace
    - leading_whitespace

opt_in_rules:
    - sorted_imports


# Files & Folder not to check
excluded:
    - "**/.build"
    - derived_data
    - ios/Modules
    - ios/build
    - vendor/bundle
