name: 'Setup Gradle Environment'
description: 'Common setup for Gradle builds with JDK 21 and environment variables'

inputs:
  gradle-cache-disabled:
    description: 'Disable Gradle cache (default: false = cache enabled). Only set to true for baseline-profile workflow.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-disabled: ${{ inputs.gradle-cache-disabled }}
