package com.thomaskioko.tvmaniac.testtags.myshows

public object MyShowsTestTags {
    public const val SCREEN_TEST_TAG: String = "my_shows_screen"
    public const val TAB_ROW: String = "my_shows_tab_row"
    public const val HORIZONTAL_PAGER: String = "my_shows_horizontal_pager"
    public const val CONTINUE_WATCHING_TAB: String = "my_shows_tab_0"
    public const val START_WATCHING_TAB: String = "my_shows_tab_1"
    public const val MY_SHOWS_GRID_TEST_TAG: String = "my_shows_grid"
    public const val MY_SHOWS_LIST_TEST_TAG: String = "my_shows_list"
    public const val MY_SHOWS_COMPACT_TEST_TAG: String = "my_shows_compact"
    public const val MY_SHOWS_DETAILED_TEST_TAG: String = "my_shows_detailed"
    public const val EMPTY_STATE_TEST_TAG: String = "my_shows_empty_state"
    public const val SEARCH_BUTTON_TEST_TAG: String = "my_shows_search_button"
    public const val SEARCH_BAR_TEST_TAG: String = "my_shows_search_bar"
    public const val LAYOUT_MENU_BUTTON_TEST_TAG: String = "my_shows_layout_menu_button"
    public const val LAYOUT_MENU_TEST_TAG: String = "my_shows_layout_menu"
    public const val LAYOUT_MENU_LOCKED_SECTION_TEST_TAG: String = "my_shows_layout_menu_locked_section"
    public const val LAYOUT_MENU_ITEM_GRID_TEST_TAG: String = "my_shows_layout_menu_item_grid"
    public const val LAYOUT_MENU_ITEM_LIST_TEST_TAG: String = "my_shows_layout_menu_item_list"
    public const val LAYOUT_MENU_ITEM_COMPACT_TEST_TAG: String = "my_shows_layout_menu_item_compact"
    public const val LAYOUT_MENU_ITEM_DETAILED_TEST_TAG: String = "my_shows_layout_menu_item_detailed"
    public const val SORT_BUTTON_TEST_TAG: String = "my_shows_sort_button"
    public const val SORT_SHEET_TEST_TAG: String = "my_shows_sort_sheet"
    public const val MY_SHOWS_INDICATOR: String = "my_shows_loading_indicator"
    public fun showCard(traktId: Long): String = "my_shows_show_card_$traktId"
}
