import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension

plugins {
    alias(libs.plugins.app.application)
}

scaffold {
    app {
        applicationId("com.thomaskioko.tvmaniac")
        minify(
            rootProject.file("app/proguard-rules.pro"),
        )
    }
    useMetro()

    android {
        useCompose()
        useBaselineProfile(projects.benchmark)
        useManagedDevices()
        enableAndroidTests(
            testInstrumentationRunner = "com.thomaskioko.tvmaniac.app.test.runner.TvManiacInstrumentationRunner",
            clearPackageData = true,
        )
    }

    optIn("androidx.compose.ui.test.ExperimentalTestApi")
}

android {
    sourceSets {
        getByName("test") {
            kotlin.directories.add("src/sharedTest/kotlin")
        }
        getByName("androidTest") {
            kotlin.directories.add("src/sharedTest/kotlin")
        }
    }
}

dependencies {
    implementation(projects.androidDesignsystem)
    implementation(projects.features.root.ui)
    implementation(projects.features.root.nav)
    implementation(projects.features.root.presenter)
    implementation(projects.api.tmdb.implementation)
    implementation(projects.api.trakt.implementation)
    implementation(projects.core.appconfig.api)
    implementation(projects.core.appconfig.implementation)
    implementation(projects.core.base)
    implementation(projects.core.syncstate.api)
    implementation(projects.core.syncstate.implementation)
    implementation(projects.core.util.implementation)
    implementation(projects.core.imageloading.implementation)
    implementation(projects.core.locale.api)
    implementation(projects.core.locale.implementation)
    implementation(projects.core.tasks.implementation)
    implementation(projects.navigation.api)
    implementation(projects.navigation.implementation)
    implementation(projects.navigation.ui)
    implementation(projects.features.debug.ui)
    implementation(projects.features.discover.ui)
    implementation(projects.features.featureFlags.ui)
    implementation(projects.features.episodeSheet.ui)
    implementation(projects.features.home.ui)
    implementation(projects.features.library.ui)
    implementation(projects.features.myShows.ui)
    implementation(projects.features.moreShows.ui)
    implementation(projects.features.profile.ui)
    implementation(projects.features.progress.ui)
    implementation(projects.features.search.ui)
    implementation(projects.features.seasonDetails.ui)
    implementation(projects.features.settings.ui)
    implementation(projects.features.showDetails.ui)
    implementation(projects.features.showList.ui)
    implementation(projects.features.trailers.ui)
    implementation(projects.features.root.presenter)
    implementation(projects.core.logger.api)
    implementation(projects.core.logger.implementation)
    implementation(projects.core.featureFlags.api)
    implementation(projects.core.featureFlags.implementation)
    implementation(projects.data.cast.implementation)
    implementation(projects.data.connectedAccount.implementation)
    implementation(projects.data.episode.implementation)
    implementation(projects.data.featuredshows.api)
    implementation(projects.data.featuredshows.implementation)
    implementation(projects.data.genre.implementation)
    implementation(projects.data.traktauth.api)
    implementation(projects.data.traktauth.implementation)
    implementation(projects.data.popularshows.api)
    implementation(projects.data.popularshows.implementation)
    implementation(projects.data.recommendedshows.implementation)
    implementation(projects.data.requestManager.api)
    implementation(projects.data.requestManager.implementation)
    implementation(projects.data.search.implementation)
    implementation(projects.data.seasondetails.api)
    implementation(projects.data.seasondetails.implementation)
    implementation(projects.data.seasons.implementation)
    implementation(projects.data.showdetails.api)
    implementation(projects.data.showdetails.implementation)
    implementation(projects.data.shows.implementation)
    implementation(projects.data.similar.implementation)
    implementation(projects.data.topratedshows.api)
    implementation(projects.data.topratedshows.implementation)
    implementation(projects.data.trailers.implementation)
    implementation(projects.data.trendingshows.api)
    implementation(projects.data.trendingshows.implementation)
    implementation(projects.data.upcomingshows.api)
    implementation(projects.data.upcomingshows.implementation)
    implementation(projects.data.watchStatus.implementation)
    implementation(projects.data.watchproviders.api)
    implementation(projects.data.watchproviders.implementation)
    implementation(projects.data.user.implementation)
    implementation(projects.data.database.sqldelight)
    implementation(projects.data.datastore.api)
    implementation(projects.data.datastore.implementation)
    implementation(projects.domain.theme)
    implementation(projects.domain.calendar)
    implementation(projects.domain.discover)
    implementation(projects.domain.episode)
    implementation(projects.domain.followedshows)
    implementation(projects.domain.genre)
    implementation(projects.domain.notifications)
    implementation(projects.domain.seasondetails)
    implementation(projects.domain.showdetails)
    implementation(projects.domain.similarshows)
    implementation(projects.domain.settings)
    implementation(projects.domain.continueWatching)
    implementation(projects.domain.favorites)
    implementation(projects.domain.library)
    implementation(projects.domain.recentlyWatched)
    implementation(projects.domain.syncActivity)
    implementation(projects.domain.user)
    implementation(projects.domain.logout)
    implementation(projects.features.debug.presenter)
    implementation(projects.features.calendar.presenter)
    implementation(projects.features.discover.presenter)
    implementation(projects.features.episodeSheet.presenter)
    implementation(projects.features.genreShows.presenter)
    implementation(projects.features.library.presenter)
    implementation(projects.features.home.presenter)
    implementation(projects.features.moreShows.presenter)
    implementation(projects.features.search.presenter)
    implementation(projects.features.seasonDetails.presenter)
    implementation(projects.features.settings.presenter)
    implementation(projects.features.profile.presenter)
    implementation(projects.features.progress.presenter)
    implementation(projects.features.showDetails.presenter)
    implementation(projects.features.showList.presenter)
    implementation(projects.features.trailers.presenter)
    implementation(projects.features.upnext.presenter)
    implementation(projects.features.showDetails.nav)
    implementation(projects.features.showList.nav)
    implementation(projects.features.episodeSheet.nav)
    implementation(projects.features.episodeSheet.nav)
    implementation(projects.features.home.nav)
    implementation(projects.features.discover.nav)
    implementation(projects.features.library.nav)
    implementation(projects.features.profile.nav)
    implementation(projects.features.progress.nav)
    implementation(projects.data.traktlists.implementation)
    implementation(projects.domain.traktlists)
    implementation(projects.core.util.api)
    implementation(projects.core.view)
    implementation(projects.data.calendar.api)
    implementation(projects.data.followedshows.api)
    implementation(projects.data.genre.api)
    implementation(projects.data.user.api)
    implementation(projects.i18n.api)

    implementation(projects.core.networkUtil.implementation)
    implementation(projects.core.notifications.api)
    implementation(projects.core.notifications.implementation)
    implementation(projects.core.connectivity.implementation)
    implementation(projects.core.tasks.api)
    implementation(projects.data.followedshows.implementation)
    implementation(projects.data.library.implementation)
    implementation(projects.data.syncActivity.implementation)
    implementation(projects.data.upnext.implementation)
    implementation(projects.data.continueWatching.implementation)
    implementation(projects.data.startWatching.api)
    implementation(projects.data.startWatching.implementation)
    implementation(projects.data.favorites.api)
    implementation(projects.data.favorites.implementation)
    implementation(projects.data.watchlistPrefs.implementation)
    implementation(projects.i18n.generator)
    implementation(projects.i18n.implementation)
    implementation(projects.data.calendar.implementation)
    implementation(projects.data.episode.api)
    implementation(projects.data.library.api)
    implementation(projects.data.search.api)
    implementation(projects.data.syncActivity.api)
    implementation(projects.data.traktlists.api)
    implementation(projects.data.upnext.api)
    implementation(projects.features.debug.nav)
    implementation(projects.features.moreShows.nav)
    implementation(projects.features.search.nav)
    implementation(projects.features.seasonDetails.nav)
    implementation(projects.features.settings.nav)
    implementation(projects.features.trailers.nav)
    implementation(projects.data.watchlistPrefs.api)
    implementation(projects.domain.continueWatching)
    implementation(projects.domain.startWatching)
    implementation(projects.features.myShows.nav)
    implementation(projects.features.myShows.presenter)
    implementation(projects.features.continueWatching.presenter)
    implementation(projects.features.startWatching.presenter)
    implementation(projects.domain.featureFlags)
    implementation(projects.features.featureFlags.nav)
    implementation(projects.features.featureFlags.presenter)

    implementation(libs.androidx.compose.activity)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.datastore.preference)
    implementation(libs.androidx.work.runtime)
    //noinspection LoginCredentials
    implementation(libs.appauth)

    implementation(libs.decompose.decompose)

    implementation(libs.androidx.datastore.core)
    implementation(libs.androidx.savedstate)
    implementation(libs.sqldelight.runtime)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.runtime)
    implementation(libs.androidx.compose.ui.ui)
    implementation(libs.coroutines.core)
    implementation(libs.ktor.core)
    implementation(libs.firebase.config)
    implementation(libs.androidx.compose.material3.windowsize)

    testRuntimeOnly(projects.core.notifications.implementation)

    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.crashlytics)

    testImplementation(projects.api.tmdb.api)
    testImplementation(projects.api.trakt.api)
    testImplementation(projects.core.connectivity.api)
    testImplementation(projects.core.integration.infra)
    testImplementation(projects.core.integration.ui)
    testImplementation(projects.core.testTags)
    testImplementation(projects.data.traktauth.testing)
    testImplementation(projects.features.genreShows.nav)
    testImplementation(projects.core.locale.testing)
    testImplementation(projects.core.util.testing)

    testImplementation(libs.firebase.config)
    testImplementation(libs.androidx.monitor)
    testImplementation(libs.androidx.compose.ui.test)
    testImplementation(libs.androidx.work.testing)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.kotest.assertions)
    testImplementation(libs.kotlin.test.junit)
    testImplementation(libs.turbine)
    testImplementation(libs.ktor.core)
    testImplementation(libs.ktor.http)
    testImplementation(libs.robolectric.annotations)

    testRuntimeOnly(libs.androidx.test.core)
    testRuntimeOnly(libs.robolectric)
    testRuntimeOnly(libs.androidx.compose.ui.test.manifest)

    androidTestImplementation(libs.firebase.config)
    androidTestImplementation(libs.robolectric.annotations)
    androidTestImplementation(projects.api.tmdb.api)
    androidTestImplementation(projects.api.trakt.api)
    androidTestImplementation(projects.core.connectivity.api)
    androidTestImplementation(projects.core.integration.infra)
    androidTestImplementation(projects.core.integration.ui)
    androidTestImplementation(projects.core.testTags)
    androidTestImplementation(projects.data.traktauth.testing)
    androidTestImplementation(projects.core.locale.testing)
    androidTestImplementation(projects.core.util.testing)

    androidTestImplementation(libs.androidx.compose.ui.test)
    androidTestImplementation(libs.androidx.monitor)
    androidTestImplementation(libs.androidx.runner)
    androidTestImplementation(libs.androidx.work.testing)
    androidTestImplementation(libs.coroutines.test)
    androidTestImplementation(libs.kotest.assertions)
    androidTestImplementation(libs.kotlin.test.junit)
    androidTestImplementation(libs.ktor.core)
    androidTestImplementation(libs.metro.runtime)
    androidTestImplementation(libs.ktor.http)

    androidTestRuntimeOnly(libs.androidx.test.core)
}

val hasGoogleServicesConfig =
    file("google-services.json").exists() ||
        file("src/debug/google-services.json").exists() ||
        file("src/release/google-services.json").exists()

if (hasGoogleServicesConfig) {
    apply(plugin = libs.plugins.google.services.get().pluginId)
    apply(plugin = libs.plugins.firebase.crashlytics.gradle.get().pluginId)
}

afterEvaluate {
    if (pluginManager.hasPlugin("com.google.firebase.crashlytics")) {
        android.buildTypes.getByName("release") {
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = true
            }
        }
    }
}
