package com.thomaskioko.tvmaniac.compose.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

val green = Color(0xFF00b300)
val grey = Color(0xFF808080)

val md_theme_light_primary = Color(0xFF0049c7)
val md_theme_light_primaryContainer = Color(0xFFdbe8f8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFF3947EA)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFe6f1fa)
val md_theme_light_onSurface = Color(0xFF1F2123)
val md_theme_light_outline = Color(0xFF1646F7)

val md_theme_dark_primary = Color(0xFF1F2123)
val md_theme_dark_primaryContainer = Color(0xFF1F2123)
val md_theme_dark_onPrimary = Color(0xFFE0E0FF)
val md_theme_dark_secondary = Color(0xFFF7d633)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_error = Color(0xFFBA1A1A)
val md_theme_dark_background = Color(0xFF373737)
val md_theme_dark_onBackground = Color(0xFFE0E0FF)
val md_theme_dark_surface = Color(0xFF43474c)
val md_theme_dark_onSurface = Color(0xFFF8FDFF)
val md_theme_dark_outline = Color(0xFF1F2123)

val md_theme_terminal_primary = Color(0xFF0A0A0A)
val md_theme_terminal_primaryContainer = Color(0xFF0A0A0A)
val md_theme_terminal_onPrimary = Color(0xFFE0E0FF)
val md_theme_terminal_secondary = Color(0xFF20C020)
val md_theme_terminal_onSecondary = Color(0xFFFFFFFF)
val md_theme_terminal_error = Color(0xFFCF6679)
val md_theme_terminal_background = Color(0xFF000000)
val md_theme_terminal_onBackground = Color(0xFFE0E0FF)
val md_theme_terminal_surface = Color(0xFF121212)
val md_theme_terminal_onSurface = Color(0xFFF8FDFF)
val md_theme_terminal_surfaceVariant = Color(0xFF1E1E1E)
val md_theme_terminal_onSurfaceVariant = Color(0xFFB0B0B0)
val md_theme_terminal_outline = Color(0xFF2C2C2C)

val md_theme_autumn_primary = Color(0xFF8B4513)
val md_theme_autumn_primaryContainer = Color(0xFFF5E6D3)
val md_theme_autumn_onPrimary = Color(0xFFFFFAF0)
val md_theme_autumn_secondary = Color(0xFFCD853F)
val md_theme_autumn_onSecondary = Color(0xFFFFFFFF)
val md_theme_autumn_error = Color(0xFF8B0000)
val md_theme_autumn_background = Color(0xFFFAF0E6)
val md_theme_autumn_onBackground = Color(0xFF3E2723)
val md_theme_autumn_surface = Color(0xFFFFF8DC)
val md_theme_autumn_onSurface = Color(0xFF3E2723)
val md_theme_autumn_surfaceVariant = Color(0xFFEFEBE9)
val md_theme_autumn_onSurfaceVariant = Color(0xFF5D4037)
val md_theme_autumn_outline = Color(0xFFA1887F)

val md_theme_aqua_primary = Color(0xFF19232B)
val md_theme_aqua_primaryContainer = Color(0xFF1B2933)
val md_theme_aqua_onPrimary = Color(0xFFFFFFFF)
val md_theme_aqua_secondary = Color(0xFF3FD2E6)
val md_theme_aqua_onSecondary = Color(0xFFFFFFFF)
val md_theme_aqua_error = Color(0xFFF84F44)
val md_theme_aqua_background = Color(0xFF161A20)
val md_theme_aqua_onBackground = Color(0xFFFFFFFF)
val md_theme_aqua_surface = Color(0xFF19232B)
val md_theme_aqua_onSurface = Color(0xFFFFFFFF)
val md_theme_aqua_surfaceVariant = Color(0xFF212835)
val md_theme_aqua_onSurfaceVariant = Color(0xFF8A9BAA)
val md_theme_aqua_outline = Color(0xFF1E3C4A)

val md_theme_amber_primary = Color(0xFF261A0A)
val md_theme_amber_primaryContainer = Color(0xFF261A0A)
val md_theme_amber_onPrimary = Color(0xFFFF8C00)
val md_theme_amber_secondary = Color(0xFFFF9500)
val md_theme_amber_onSecondary = Color(0xFF1A1005)
val md_theme_amber_error = Color(0xFFFF6B35)
val md_theme_amber_background = Color(0xFF1A1005)
val md_theme_amber_onBackground = Color(0xFFFF8C00)
val md_theme_amber_surface = Color(0xFF261A0A)
val md_theme_amber_onSurface = Color(0xFFFF8C00)
val md_theme_amber_surfaceVariant = Color(0xFF33220D)
val md_theme_amber_onSurfaceVariant = Color(0xFFCC7000)
val md_theme_amber_outline = Color(0xFF995500)

val md_theme_snow_primary = Color(0xFF1A1A1A)
val md_theme_snow_primaryContainer = Color(0xFF1A1A1A)
val md_theme_snow_onPrimary = Color(0xFFF0F0F0)
val md_theme_snow_secondary = Color(0xFFFFFFFF)
val md_theme_snow_onSecondary = Color(0xFF0A0A0A)
val md_theme_snow_error = Color(0xFFBA1A1A)
val md_theme_snow_background = Color(0xFF0A0A0A)
val md_theme_snow_onBackground = Color(0xFFF0F0F0)
val md_theme_snow_surface = Color(0xFF1A1A1A)
val md_theme_snow_onSurface = Color(0xFFF0F0F0)
val md_theme_snow_surfaceVariant = Color(0xFF2A2A2A)
val md_theme_snow_onSurfaceVariant = Color(0xFFA0A0A0)
val md_theme_snow_outline = Color(0xFF606060)

val md_theme_crimson_primary = Color(0xFF2A1519)
val md_theme_crimson_primaryContainer = Color(0xFF2A1519)
val md_theme_crimson_onPrimary = Color(0xFFFF4D6A)
val md_theme_crimson_secondary = Color(0xFFFF6B8A)
val md_theme_crimson_onSecondary = Color(0xFF150A0D)
val md_theme_crimson_error = Color(0xFFFF3333)
val md_theme_crimson_background = Color(0xFF150A0D)
val md_theme_crimson_onBackground = Color(0xFFFF4D6A)
val md_theme_crimson_surface = Color(0xFF2A1519)
val md_theme_crimson_onSurface = Color(0xFFFF4D6A)
val md_theme_crimson_surfaceVariant = Color(0xFF3D1F25)
val md_theme_crimson_onSurfaceVariant = Color(0xFFB03050)
val md_theme_crimson_outline = Color(0xFF802040)

@Composable
fun backgroundGradient(): List<Color> {
    return listOf(
        MaterialTheme.colorScheme.background,
        MaterialTheme.colorScheme.background.copy(alpha = 0.9F),
        MaterialTheme.colorScheme.background.copy(alpha = 0.8F),
        MaterialTheme.colorScheme.background.copy(alpha = 0.7F),
        Color.Transparent,
    )
}
