package com.thomaskioko.tvmaniac.compose.theme

import androidx.compose.ui.graphics.Color

public val green: Color = Color(0xFF00b300)
public val grey: Color = Color(0xFF808080)

public val md_theme_light_primary: Color = Color(0xFF0049c7)
public val md_theme_light_primaryContainer: Color = Color(0xFFdbe8f8)
public val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF)
public val md_theme_light_secondary: Color = Color(0xFF3947EA)
public val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_light_error: Color = Color(0xFFBA1A1A)
public val md_theme_light_background: Color = Color(0xFFF8FDFF)
public val md_theme_light_onBackground: Color = Color(0xFF001F25)
public val md_theme_light_surface: Color = Color(0xFFe6f1fa)
public val md_theme_light_onSurface: Color = Color(0xFF1F2123)
public val md_theme_light_outline: Color = Color(0xFF1646F7)

public val md_theme_dark_primary: Color = Color(0xFF1F2123)
public val md_theme_dark_primaryContainer: Color = Color(0xFF1F2123)
public val md_theme_dark_onPrimary: Color = Color(0xFFE0E0FF)
public val md_theme_dark_secondary: Color = Color(0xFFF7d633)
public val md_theme_dark_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_dark_error: Color = Color(0xFFBA1A1A)
public val md_theme_dark_background: Color = Color(0xFF373737)
public val md_theme_dark_onBackground: Color = Color(0xFFE0E0FF)
public val md_theme_dark_surface: Color = Color(0xFF43474c)
public val md_theme_dark_onSurface: Color = Color(0xFFF8FDFF)
public val md_theme_dark_outline: Color = Color(0xFF1F2123)

public val md_theme_terminal_primary: Color = Color(0xFF0A0A0A)
public val md_theme_terminal_primaryContainer: Color = Color(0xFF0A0A0A)
public val md_theme_terminal_onPrimary: Color = Color(0xFFE0E0FF)
public val md_theme_terminal_secondary: Color = Color(0xFF20C020)
public val md_theme_terminal_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_terminal_error: Color = Color(0xFFCF6679)
public val md_theme_terminal_background: Color = Color(0xFF000000)
public val md_theme_terminal_onBackground: Color = Color(0xFFE0E0FF)
public val md_theme_terminal_surface: Color = Color(0xFF121212)
public val md_theme_terminal_onSurface: Color = Color(0xFFF8FDFF)
public val md_theme_terminal_surfaceVariant: Color = Color(0xFF1E1E1E)
public val md_theme_terminal_onSurfaceVariant: Color = Color(0xFFB0B0B0)
public val md_theme_terminal_outline: Color = Color(0xFF2C2C2C)

public val md_theme_autumn_primary: Color = Color(0xFF8B4513)
public val md_theme_autumn_primaryContainer: Color = Color(0xFFF5E6D3)
public val md_theme_autumn_onPrimary: Color = Color(0xFFFFFAF0)
public val md_theme_autumn_secondary: Color = Color(0xFFCD853F)
public val md_theme_autumn_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_autumn_error: Color = Color(0xFF8B0000)
public val md_theme_autumn_background: Color = Color(0xFFFAF0E6)
public val md_theme_autumn_onBackground: Color = Color(0xFF3E2723)
public val md_theme_autumn_surface: Color = Color(0xFFFFF8DC)
public val md_theme_autumn_onSurface: Color = Color(0xFF3E2723)
public val md_theme_autumn_surfaceVariant: Color = Color(0xFFEFEBE9)
public val md_theme_autumn_onSurfaceVariant: Color = Color(0xFF5D4037)
public val md_theme_autumn_outline: Color = Color(0xFFA1887F)

public val md_theme_aqua_primary: Color = Color(0xFF19232B)
public val md_theme_aqua_primaryContainer: Color = Color(0xFF1B2933)
public val md_theme_aqua_onPrimary: Color = Color(0xFFFFFFFF)
public val md_theme_aqua_secondary: Color = Color(0xFF3FD2E6)
public val md_theme_aqua_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_aqua_error: Color = Color(0xFFF84F44)
public val md_theme_aqua_background: Color = Color(0xFF161A20)
public val md_theme_aqua_onBackground: Color = Color(0xFFFFFFFF)
public val md_theme_aqua_surface: Color = Color(0xFF19232B)
public val md_theme_aqua_onSurface: Color = Color(0xFFFFFFFF)
public val md_theme_aqua_surfaceVariant: Color = Color(0xFF212835)
public val md_theme_aqua_onSurfaceVariant: Color = Color(0xFF8A9BAA)
public val md_theme_aqua_outline: Color = Color(0xFF1E3C4A)

public val md_theme_amber_primary: Color = Color(0xFF261A0A)
public val md_theme_amber_primaryContainer: Color = Color(0xFF261A0A)
public val md_theme_amber_onPrimary: Color = Color(0xFFFF8C00)
public val md_theme_amber_secondary: Color = Color(0xFFFF9500)
public val md_theme_amber_onSecondary: Color = Color(0xFF1A1005)
public val md_theme_amber_error: Color = Color(0xFFFF6B35)
public val md_theme_amber_background: Color = Color(0xFF1A1005)
public val md_theme_amber_onBackground: Color = Color(0xFFFF8C00)
public val md_theme_amber_surface: Color = Color(0xFF261A0A)
public val md_theme_amber_onSurface: Color = Color(0xFFFF8C00)
public val md_theme_amber_surfaceVariant: Color = Color(0xFF33220D)
public val md_theme_amber_onSurfaceVariant: Color = Color(0xFFCC7000)
public val md_theme_amber_outline: Color = Color(0xFF995500)

public val md_theme_snow_primary: Color = Color(0xFF1A1A1A)
public val md_theme_snow_primaryContainer: Color = Color(0xFF1A1A1A)
public val md_theme_snow_onPrimary: Color = Color(0xFFF0F0F0)
public val md_theme_snow_secondary: Color = Color(0xFFC8C8CC)
public val md_theme_snow_onSecondary: Color = Color(0xFF0A0A0A)
public val md_theme_snow_error: Color = Color(0xFFBA1A1A)
public val md_theme_snow_background: Color = Color(0xFF0A0A0A)
public val md_theme_snow_onBackground: Color = Color(0xFFF0F0F0)
public val md_theme_snow_surface: Color = Color(0xFF1A1A1A)
public val md_theme_snow_onSurface: Color = Color(0xFFF0F0F0)
public val md_theme_snow_surfaceVariant: Color = Color(0xFF2A2A2A)
public val md_theme_snow_onSurfaceVariant: Color = Color(0xFFA0A0A0)
public val md_theme_snow_outline: Color = Color(0xFF606060)

public val md_theme_crimson_primary: Color = Color(0xFF2A1519)
public val md_theme_crimson_primaryContainer: Color = Color(0xFF2A1519)
public val md_theme_crimson_onPrimary: Color = Color(0xFFFF4D6A)
public val md_theme_crimson_secondary: Color = Color(0xFFFF6B8A)
public val md_theme_crimson_onSecondary: Color = Color(0xFF150A0D)
public val md_theme_crimson_error: Color = Color(0xFFFF3333)
public val md_theme_crimson_background: Color = Color(0xFF150A0D)
public val md_theme_crimson_onBackground: Color = Color(0xFFFF4D6A)
public val md_theme_crimson_surface: Color = Color(0xFF2A1519)
public val md_theme_crimson_onSurface: Color = Color(0xFFFF4D6A)
public val md_theme_crimson_surfaceVariant: Color = Color(0xFF3D1F25)
public val md_theme_crimson_onSurfaceVariant: Color = Color(0xFFB03050)
public val md_theme_crimson_outline: Color = Color(0xFF802040)
