package com.thomaskioko.tvmaniac.ui.upnext.preview

import androidx.compose.ui.tooling.preview.PreviewParameterProvider
import com.thomaskioko.tvmaniac.domain.upnext.model.UpNextSortOption
import com.thomaskioko.tvmaniac.presentation.upnext.UpNextState
import com.thomaskioko.tvmaniac.presentation.upnext.model.UpNextEpisodeUiModel
import kotlinx.collections.immutable.persistentListOf
import kotlinx.collections.immutable.toImmutableList

internal class UpNextStatePreviewParameterProvider : PreviewParameterProvider<UpNextState> {
    override val values: Sequence<UpNextState> = sequenceOf(
        UpNextState(
            isLoading = true,
            episodes = persistentListOf(),
        ),
        UpNextState(
            isLoading = false,
            episodes = persistentListOf(),
        ),
        UpNextState(
            isLoading = false,
            sortOption = UpNextSortOption.LAST_WATCHED,
            episodes = previewEpisodes(),
        ),
        UpNextState(
            isLoading = false,
            sortOption = UpNextSortOption.AIR_DATE,
            episodes = previewEpisodes(),
        ),
        UpNextState(
            isLoading = true,
            sortOption = UpNextSortOption.LAST_WATCHED,
            episodes = previewEpisodes(),
        ),
    )
}

internal class UpNextEpisodePreviewParameterProvider : PreviewParameterProvider<UpNextEpisodeUiModel> {
    override val values: Sequence<UpNextEpisodeUiModel> = sequenceOf(
        UpNextEpisodeUiModel(
            showTraktId = 1,
            showTmdbId = 1396,
            showName = "Breaking Bad",
            showPoster = null,
            showStatus = "Ended",
            showYear = "2008",
            episodeId = 101,
            episodeName = "Ozymandias",
            seasonId = 10,
            seasonNumber = 5,
            episodeNumber = 14,
            runtime = 47,
            stillPath = null,
            overview = "Everyone copes with radically changed circumstances.",
            firstAired = null,
            seasonCount = 5,
            episodeCount = 62,
            watchedCount = 55,
            totalCount = 62,
        ),
        UpNextEpisodeUiModel(
            showTraktId = 2,
            showTmdbId = 1399,
            showName = "Game of Thrones: A Very Long Title That Wraps",
            showPoster = null,
            showStatus = "Ended",
            showYear = "2011",
            episodeId = 201,
            episodeName = "The Rains of Castamere",
            seasonId = 20,
            seasonNumber = 3,
            episodeNumber = 9,
            runtime = 52,
            stillPath = null,
            overview = "Robb and Catelyn receive an important dinner invitation.",
            firstAired = null,
            seasonCount = 8,
            episodeCount = 73,
            watchedCount = 20,
            totalCount = 73,
        ),
        UpNextEpisodeUiModel(
            showTraktId = 3,
            showTmdbId = 66732,
            showName = "Stranger Things",
            showPoster = null,
            showStatus = "Returning Series",
            showYear = "2016",
            episodeId = 301,
            episodeName = null,
            seasonId = 30,
            seasonNumber = 1,
            episodeNumber = 1,
            runtime = 50,
            stillPath = null,
            overview = null,
            firstAired = null,
            seasonCount = 4,
            episodeCount = 34,
            watchedCount = 0,
            totalCount = 34,
        ),
    )
}

private fun previewEpisodes() = listOf(
    UpNextEpisodeUiModel(
        showTraktId = 1,
        showTmdbId = 1396,
        showName = "Breaking Bad",
        showPoster = null,
        showStatus = "Ended",
        showYear = "2008",
        episodeId = 101,
        episodeName = "Ozymandias",
        seasonId = 10,
        seasonNumber = 5,
        episodeNumber = 14,
        runtime = 47,
        stillPath = null,
        overview = "Everyone copes with radically changed circumstances.",
        firstAired = null,
        seasonCount = 5,
        episodeCount = 62,
        watchedCount = 55,
        totalCount = 62,
    ),
    UpNextEpisodeUiModel(
        showTraktId = 2,
        showTmdbId = 1399,
        showName = "Game of Thrones",
        showPoster = null,
        showStatus = "Ended",
        showYear = "2011",
        episodeId = 201,
        episodeName = "The Rains of Castamere",
        seasonId = 20,
        seasonNumber = 3,
        episodeNumber = 9,
        runtime = 52,
        stillPath = null,
        overview = "Robb and Catelyn receive an important dinner invitation.",
        firstAired = null,
        seasonCount = 8,
        episodeCount = 73,
        watchedCount = 20,
        totalCount = 73,
    ),
    UpNextEpisodeUiModel(
        showTraktId = 3,
        showTmdbId = 66732,
        showName = "Stranger Things",
        showPoster = null,
        showStatus = "Returning Series",
        showYear = "2016",
        episodeId = 301,
        episodeName = "Chapter One: The Vanishing of Will Byers",
        seasonId = 30,
        seasonNumber = 1,
        episodeNumber = 1,
        runtime = 50,
        stillPath = null,
        overview = "On his way home from a friend's house, young Will sees something terrifying.",
        firstAired = null,
        seasonCount = 4,
        episodeCount = 34,
        watchedCount = 0,
        totalCount = 34,
    ),
    UpNextEpisodeUiModel(
        showTraktId = 4,
        showTmdbId = 94997,
        showName = "House of the Dragon",
        showPoster = null,
        showStatus = "Returning Series",
        showYear = "2022",
        episodeId = 401,
        episodeName = "The Heirs of the Dragon",
        seasonId = 40,
        seasonNumber = 2,
        episodeNumber = 5,
        runtime = 67,
        stillPath = null,
        overview = null,
        firstAired = null,
        seasonCount = 2,
        episodeCount = 18,
        watchedCount = 12,
        totalCount = 18,
    ),
).toImmutableList()
