default_platform(:ios)

XC_PROJECT = File.absolute_path('../tv-maniac.xcodeproj')
TEST_DEVICE = "iPhone 15 Pro (17.5)"

platform :ios do
  before_all do
    if is_ci
      setup_ci
      # set Fastlane's xcodebuild -showBuildSettings timeout to a more reasonable value.
      ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '180'
    end
  end

  desc "Build iOS App"
  lane :build_tvmaniac do
    build_app(
      scheme: "tv-maniac",
      project: XC_PROJECT,
      skip_archive: true,
      skip_codesigning: true
      )
  end   

  desc "Run UI Tests"
  lane :ui_tests do
    schemes = ["SwiftUIComponents", "TvManiacUITests"]

    schemes.each { |scheme| puts "- #{scheme}" }

    schemes.each do |scheme|

      UI.message("Running #{scheme} tests at #{XC_PROJECT}")

      run_tests(
        project: XC_PROJECT,
        scheme: scheme,
        device: TEST_DEVICE,
        derived_data_path: "derived_data",
        result_bundle: true,
        output_directory: "fastlane/test_output/#{scheme}",
        output_types: "html,junit",
      )
    end
  end

  desc "Clear derived data"
  lane :clear_derived_data_lane do
    UI.message("Clearing derived data...")
    clear_derived_data
  end

end
