package com.thomaskioko.tvmaniac.testtags.settings

public object SettingsTestTags {
    public const val SCREEN_TEST_TAG: String = "settings_screen"
    public const val LIST_TEST_TAG: String = "settings_list"
    public const val BACK_BUTTON_TEST_TAG: String = "settings_back_button"
    public const val GENERAL_APPEARANCE_ROW_TEST_TAG: String = "settings_general_appearance_row"
    public const val GENERAL_LAYOUT_ROW_TEST_TAG: String = "settings_general_layout_row"
    public const val GENERAL_BEHAVIOR_ROW_TEST_TAG: String = "settings_general_behavior_row"
    public const val GENERAL_NOTIFICATIONS_ROW_TEST_TAG: String = "settings_general_notifications_row"
    public const val GENERAL_PRIVACY_ROW_TEST_TAG: String = "settings_general_privacy_row"
    public const val ACCOUNT_TRAKT_ROW_TEST_TAG: String = "settings_account_trakt_row"
    public const val ABOUT_INFO_ROW_TEST_TAG: String = "settings_about_info_row"
    public const val ABOUT_LICENSES_ROW_TEST_TAG: String = "settings_about_licenses_row"
    public const val INFO_VERSION_TEXT_TEST_TAG: String = "settings_info_version_text"
    public const val TRAKT_ACCOUNT_ROW_TEST_TAG: String = "settings_trakt_account_row"
    public const val LOGOUT_DIALOG_CONFIRM_BUTTON_TEST_TAG: String = "settings_logout_dialog_confirm"
    public const val LOGOUT_DIALOG_DISMISS_BUTTON_TEST_TAG: String = "settings_logout_dialog_dismiss"
    public const val EPISODE_NOTIFICATIONS_TOGGLE_TEST_TAG: String = "settings_episode_notifications_toggle"
    public const val HAPTIC_FEEDBACK_TOGGLE_TEST_TAG: String = "settings_haptic_feedback_toggle"
    public const val SWITCH_PROVIDER_BUTTON_TEST_TAG: String = "settings_switch_provider_button"
    public const val SWITCH_DIALOG_CONFIRM_BUTTON_TEST_TAG: String = "settings_switch_dialog_confirm"
    public const val SWITCH_DIALOG_DISMISS_BUTTON_TEST_TAG: String = "settings_switch_dialog_dismiss"
    public const val SWITCHING_INDICATOR_TEST_TAG: String = "settings_switching_indicator"
    public const val AUTH_PROCESSING_INDICATOR_TEST_TAG: String = "settings_auth_processing_indicator"
    public fun imageQualityChip(name: String): String = "settings_image_quality_${name.lowercase()}"
    public const val THEMES_LOCKED: String = "settings_themes_locked"
    public fun themeSwatch(name: String): String = "settings_theme_swatch_${name.lowercase()}"
}
